# Generated by Django 2.0.1 on 2018-06-16 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='placeholder')),
                ('image_height', models.IntegerField(default=0)),
                ('image_width', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.IntegerField()),
                ('observation_image', models.ImageField(upload_to='media')),
                ('image_width', models.IntegerField(default=844)),
                ('image_height', models.IntegerField(default=644)),
                ('observation_date', models.DateField()),
                ('observation_start_time', models.DateTimeField()),
                ('observation_end_time', models.DateTimeField()),
                ('exposure_duration', models.IntegerField(default=0)),
                ('aperture_size', models.IntegerField(default=0)),
                ('align_x0', models.IntegerField(default=0)),
                ('align_y0', models.IntegerField(default=0)),
                ('align_u0', models.IntegerField(default=0)),
                ('observation_type', models.CharField(choices=[('S', 'Standard'), ('B', 'bias'), ('F', 'flat'), ('D', 'dark')], default='S', max_length=1)),
                ('observation_filter', models.CharField(choices=[('R', 'R'), ('G', 'G'), ('B', 'B'), ('U', 'U'), ('I', 'I'), ('V', 'V')], default='I', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PhotometrySource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_pos_x', models.FloatField(default=0)),
                ('source_pos_y', models.FloatField(default=0)),
                ('source_type', models.CharField(default='target', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(max_length=200)),
                ('object_RA', models.CharField(max_length=12)),
                ('object_DEC', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='photometrysource',
            name='observation_target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hops.Target'),
        ),
        migrations.AddField(
            model_name='frame',
            name='observation_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hops.Target'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='data',
            field=models.ManyToManyField(to='hops.Frame'),
        ),
    ]
