# Generated by Django 2.0.1 on 2018-05-19 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(max_length=200)),
                ('object_ra', models.CharField(max_length=12)),
                ('object_dec', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.IntegerField()),
                ('observation_filename', models.FileField(upload_to='')),
                ('observation_date', models.DateField()),
                ('observation_start_time', models.TimeField()),
                ('observation_end_time', models.TimeField()),
                ('exposure_duration', models.IntegerField(default=0)),
                ('observation_type', models.CharField(choices=[('S', 'Standard'), ('B', 'bias'), ('F', 'flat'), ('D', 'dark')], default='S', max_length=1)),
                ('observation_filter', models.CharField(choices=[('R', 'R'), ('G', 'G'), ('B', 'B'), ('U', 'U'), ('I', 'I'), ('V', 'V')], default='I', max_length=1)),
                ('observation_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hops.Object')),
            ],
        ),
    ]
