# Generated by Django 2.0.1 on 2018-05-19 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hops', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='object_dec',
            new_name='object_DEC',
        ),
        migrations.RenameField(
            model_name='object',
            old_name='object_ra',
            new_name='object_RA',
        ),
    ]
