# Generated by Django 2.0.1 on 2018-06-17 09:33

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='observation_data',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
