# Generated by Django 2.0.1 on 2018-05-19 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hops', '0002_auto_20180519_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datasets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='Observation',
            new_name='Frame',
        ),
        migrations.AddField(
            model_name='datasets',
            name='frames',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hops.Frame'),
        ),
    ]
