# Generated by Django 2.0.1 on 2018-06-17 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hops', '0002_frame_observation_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frame',
            name='observation_data',
        ),
    ]
