# Generated by Django 2.0.1 on 2018-06-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hops', '0003_remove_frame_observation_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='photometrysource',
            name='aperture_size',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='frame',
            name='aperture_size',
            field=models.IntegerField(default=7),
        ),
    ]
