# Generated by Django 2.0.1 on 2018-05-19 17:53

from django.db import migrations


class Migration(migrations.Migration):
    
    atomic = False
    dependencies = [
        ('hops', '0003_auto_20180519_1744'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Object',
            new_name='Target',
        ),
    ]
