# Generated by Django 2.0.1 on 2018-05-20 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hops', '0004_auto_20180519_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasets',
            name='frames',
        ),
        migrations.DeleteModel(
            name='Datasets',
        ),
    ]
