# Generated by Django 2.0.1 on 2018-06-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hops', '0004_auto_20180617_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='photometrysource',
            name='source_pos_r',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='photometrysource',
            name='source_pos_u',
            field=models.FloatField(default=0),
        ),
    ]
