# Generated by Django 2.0.1 on 2018-05-22 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hops', '0007_dataset_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='frames',
        ),
        migrations.DeleteModel(
            name='Dataset',
        ),
    ]
