# Generated by Django 2.0.1 on 2018-05-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hops', '0010_dataset_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='observation_image',
            field=models.ImageField(default='qatar1b-125.fit', upload_to='uploads'),
            preserve_default=False,
        ),
    ]
