# Generated by Django 2.0.1 on 2018-05-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hops', '0011_frame_observation_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frame',
            name='observation_filename',
        ),
        migrations.AlterField(
            model_name='frame',
            name='observation_image',
            field=models.ImageField(upload_to='hops/media'),
        ),
    ]
