# Generated by Django 2.0.1 on 2018-05-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hops', '0015_dataset_finder_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='finder_image',
            field=models.ImageField(upload_to='hops/media/'),
        ),
    ]
