# Generated by Django 2.0.1 on 2018-05-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hops', '0017_auto_20180530_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='finder_image',
            field=models.ImageField(blank=True, upload_to='hops/static/hops/'),
        ),
    ]
