# Generated by Django 2.0.1 on 2018-05-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hops', '0018_auto_20180530_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='finder_image',
            field=models.ImageField(blank=True, upload_to='static'),
        ),
        migrations.AlterField(
            model_name='frame',
            name='observation_image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
