# Generated by Django 2.0.1 on 2018-06-02 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hops', '0020_remove_dataset_finder_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotometrySource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourcePosX', models.IntegerField(default=0)),
                ('sourcePosY', models.IntegerField(default=0)),
                ('sourceCount', models.IntegerField(default=0)),
                ('observation_frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hops.Frame')),
            ],
        ),
    ]
