# Generated by Django 2.0.1 on 2018-06-02 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hops', '0021_photometrysource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photometrysource',
            name='observation_frame',
        ),
        migrations.AddField(
            model_name='photometrysource',
            name='observation_target',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hops.Target'),
            preserve_default=False,
        ),
    ]
