# Generated by Django 2.0.1 on 2018-06-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hops', '0022_auto_20180602_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photometrysource',
            name='sourcePosX',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='photometrysource',
            name='sourcePosY',
            field=models.FloatField(default=0),
        ),
    ]
